[package]
name = "flatcrawl-crawler"
version = "1.0.0"
authors = ["Florian Schnell <floschnell@gmail.com>"]

[dependencies]
kuchiki = {version = "0.7.2"}
reqwest = {version = "0.8.8"}
regex = "1.0.5"
chrono = "0.4.6"
lapin-futures = "0.13.0"
tokio-core = "0.1.17"
futures = "0.1.24"
serde_json = "1.0.27"
serde = "1.0.79"
serde_derive = "1.0.79"
dns-lookup = "0.9.1"
config = "0.9.0"
url = "1.7.1"