[package]
name = "flatcrawl-crawler"
version = "1.0.0"
authors = ["Florian Schnell <floschnell@gmail.com>"]

[dependencies]
kuchiki = {version = "0.6.0"}
reqwest = {version = "0.8.2"}
regex = "0.2"
chrono = "0.4"
lapin-futures = "^0.10"
tokio-core = "0.1"
futures = "0.1"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
dns-lookup = "0.8.1"
config = "0.7"
url = "1.7.1"