# this is a sample configuration file
# the program will pick it up, if it is named config.toml

# number of threads on which the crawlers will be executed
thread_count = 4

# address of the geocoding service
nominatim_url = "https://nominatim.openstreetmap.org/search"

# if this is a testrun
# during a testrun no results will be sent
test = false

# amqp broker details
# you can point this for instance to a RabbitMQ broker
[amqp]
host = "yourdomain.de"
username = "username"
password = "password"
queue = "flats"